# Generated by Django 4.0.3 on 2022-03-27 16:44

import Cottage_garden_project.main.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('type', models.CharField(blank=True, choices=[('Perennial plants', 'Perennial plants'), ('Annual plants', 'Annual plants'), ('Home plants', 'Home plants')], max_length=16, null=True)),
                ('address', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gardens/', validators=[Cottage_garden_project.main.models.MaxFileSizeInMBValidator(5)])),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('name', 'user_profile')},
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('type', models.CharField(choices=[('Fruit tree', 'Fruit tree'), ('Evergreen tree', 'Evergreen tree'), ('Bush', 'Bush'), ('Climbing plants', 'Climbing plants'), ('Vegetable', 'Vegetable'), ('Flower', 'Flower')], max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sort', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='gardens/', validators=[Cottage_garden_project.main.models.MaxFileSizeInMBValidator(5)])),
                ('year', models.DateField()),
                ('plant_protections', models.CharField(max_length=10)),
                ('harvest_quantity', models.FloatField()),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.garden')),
            ],
        ),
        migrations.CreateModel(
            name='PlantProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UseFullTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=10)),
                ('text_field', models.CharField(max_length=50)),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_protection',
            field=models.ManyToManyField(to='main.plantprotection'),
        ),
    ]
