# Generated by Django 4.0.3 on 2022-03-28 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='garden',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='garden',
            name='type',
            field=models.CharField(choices=[('Perennial plants', 'Perennial plants'), ('Annual plants', 'Annual plants'), ('Home plants', 'Home plants')], default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='garden',
            unique_together={('user', 'name')},
        ),
        migrations.RemoveField(
            model_name='garden',
            name='user_profile',
        ),
    ]
