# Generated by Django 4.0.3 on 2022-04-03 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_garden_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('Fruit tree', 'Fruit tree'), ('Evergreen tree', 'Evergreen tree'), ('Bush', 'Bush'), ('Climbing plants', 'Climbing plants'), ('Vegetable', 'Vegetable'), ('Flower', 'Flower'), ('Other', 'Other')], max_length=15, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
