# Generated by Django 4.0.3 on 2022-04-03 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sort',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
