# Generated by Django 4.0.3 on 2022-04-09 18:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
