# Generated by Django 4.0.3 on 2022-04-09 21:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
