# Generated by Django 4.0.3 on 2022-04-11 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_remove_plant_plant_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_protection',
            field=models.ManyToManyField(to='main.plantprotection'),
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
