# Generated by Django 4.0.3 on 2022-04-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_plant_plant_protection_plant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='user',
        ),
    ]
